name: Docker

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build, and tag
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # tag it.
          docker build -t larased .
          # Let's grab the latest version of a laravel application to test against
          composer create-project --prefer-dist laravel/laravel app
          # Run
          docker run --rm -v `pwd`:/var/larased:ro larased