name: PHP Composer

on:
  push:
    branches: [ dev, main, feature/*, bugfix/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version: [ '7.3', '7.4', '8.0' ]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none
      - run: composer install --ansi
        working-directory: ${{ matrix.directory }}
      - name: Prepare tests
        run: composer create-project laravel/laravel sample-apps/laravel-app
      - name: Test
        run: |
          composer install
          vendor/bin/phpunit --configuration=phpunit.xml

      - name: Test Bin
        run: |
          php larased

      - name: Install Jq
        run: sudo apt-get install -y jq

      - name: Getting version right
        id: package-version
        run: |
          output=$(jq -rc '.version' composer.json)
          echo "::set-output name=PACKAGE_VERSION::$output"
        shell: bash
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.test.outputs.PACKAGE_VERSION }}
          release_name: Release ${{ needs.test.outputs.PACKAGE_VERSION }}
          draft: false
          prerelease: false
