name: PHP Composer

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare tests
        run: composer create-project laravel/laravel sample-apps/laravel-app

      - name: Test
        run: |
          composer install
          vendor/bin/phpunit --configuration=phpunit.xml
      
      - name: Test Bin
        run: |
          alias larased_bin="php $(pwd)/bin/larased"
          larased_bin